#!/bin/sh
#
# Generate a .env file with random credentials for the Grafana OnCall
# docker compose (hobby) setup.
#
# Usage: ./scripts/init-env.sh [--force] [--demo]
#
#   --force   overwrite an existing .env; the old one is kept as
#             .env.bak.<timestamp> so nothing is lost
#   --demo    also generate DEMO_USERS_PASSWORD, used by demo accounts;
#             the value is written to .env and never printed
#
# The file is written as ./.env in the current working directory, with mode
# 600. Every generated value is alphanumeric, so it is safe unquoted in .env
# and in docker compose interpolation.
#
set -eu

ENV_FILE="./.env"
FORCE=0
DEMO=0

usage() {
	cat <<'USAGE'
Usage: init-env.sh [--force] [--demo]

  --force   overwrite an existing .env (the old file is backed up to
            .env.bak.<timestamp>)
  --demo    additionally generate DEMO_USERS_PASSWORD for demo accounts
  -h        show this help

Writes ./.env with mode 600 and prints the generated Grafana admin password
once.
USAGE
}

while [ $# -gt 0 ]; do
	case "$1" in
	--force) FORCE=1 ;;
	--demo) DEMO=1 ;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		printf 'init-env.sh: unknown option: %s\n\n' "$1" >&2
		usage >&2
		exit 2
		;;
	esac
	shift
done

if [ -e "$ENV_FILE" ] && [ "$FORCE" -eq 0 ]; then
	printf 'init-env.sh: %s already exists, nothing was changed.\n' "$ENV_FILE" >&2
	printf 'Re-run with --force to rotate every credential (the old file is backed up).\n' >&2
	exit 1
fi

# Pick a source of randomness: openssl if present, /dev/urandom otherwise.
if command -v openssl >/dev/null 2>&1; then
	RANDOM_SOURCE=openssl
elif [ -r /dev/urandom ]; then
	RANDOM_SOURCE=urandom
else
	printf 'init-env.sh: no randomness available (need openssl or /dev/urandom).\n' >&2
	exit 1
fi

# Emit a batch of random alphanumeric characters (length is not exact).
random_chunk() {
	if [ "$RANDOM_SOURCE" = openssl ]; then
		openssl rand -base64 192 | tr -dc 'A-Za-z0-9'
	else
		LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 256
	fi
}

# random_alnum <length> -- exactly <length> random alphanumeric characters.
random_alnum() {
	_want="$1"
	_out=""
	_tries=0
	while [ "${#_out}" -lt "$_want" ]; do
		_tries=$((_tries + 1))
		if [ "$_tries" -gt 20 ]; then
			printf 'init-env.sh: could not gather random data.\n' >&2
			exit 1
		fi
		_out="$_out$(random_chunk)"
	done
	printf '%s' "$_out" | cut -c"1-$_want"
}

SECRET_KEY="$(random_alnum 64)"
MIRAGE_SECRET_KEY="$(random_alnum 40)"
MIRAGE_CIPHER_IV="$(random_alnum 16)"
MYSQL_PASSWORD="$(random_alnum 32)"
# The bundled MySQL is reached as root (MYSQL_USER defaults to root), and the
# healthcheck plus the Grafana database user both authenticate with
# MYSQL_PASSWORD, so root's password has to be the same value.
MYSQL_ROOT_PASSWORD="$MYSQL_PASSWORD"
RABBITMQ_PASSWORD="$(random_alnum 32)"
GRAFANA_ADMIN_PASSWORD="$(random_alnum 32)"
GRAFANA_USER="admin"

if [ -e "$ENV_FILE" ]; then
	BACKUP="$ENV_FILE.bak.$(date +%Y%m%d%H%M%S)"
	cp "$ENV_FILE" "$BACKUP"
	chmod 600 "$BACKUP"
	printf 'Backed up the existing .env to %s\n' "$BACKUP"
fi

# Create the file with no group/other permissions from the start.
umask 077

cat >"$ENV_FILE" <<ENVFILE
# Generated by scripts/init-env.sh -- do not commit this file.
# Rotate every credential with: ./scripts/init-env.sh --force
# (the previous file is kept as .env.bak.<timestamp>), then restart the stack.

# ---------------------------------------------------------------------------
# Deployment settings -- safe to edit
# ---------------------------------------------------------------------------

# Root URL of the OnCall engine, used as BASE_URL by the engine.
DOMAIN=http://localhost:8080

# Which compose profiles to start. Drop with_grafana to use your own Grafana;
# add with_prometheus for a local Prometheus scraping OnCall metrics.
COMPOSE_PROFILES=with_grafana

# Tag of the grafana/* image used by the bundled grafana service.
GRAFANA_IMAGE=grafana:latest

# Grafana admin username (the password is GRAFANA_ADMIN_PASSWORD below).
GRAFANA_USER=$GRAFANA_USER

# Prometheus exporter, docker-compose.yml only. To enable it set this to True
# and put a token in PROMETHEUS_EXPORTER_SECRET matching prometheus.yml.
FEATURE_PROMETHEUS_EXPORTER_ENABLED=false
PROMETHEUS_EXPORTER_SECRET=

# docker-compose-mysql-rabbitmq.yml only: which MySQL account and host the
# engine and Grafana connect to.
MYSQL_USER=root
MYSQL_HOST=mysql

# ---------------------------------------------------------------------------
# Secrets -- generated randomly, never commit or share them
# ---------------------------------------------------------------------------

# Django secret key for the engine. Changing it invalidates existing sessions
# and tokens.
SECRET_KEY=$SECRET_KEY

# django-mirage-field encryption of stored credentials. settings.hobby (the
# settings module both compose files use) derives MIRAGE_SECRET_KEY from
# SECRET_KEY and pins a fixed IV, so these two only take effect with a
# settings module that reads them, such as settings.dev. Changing them makes
# already-encrypted values unreadable.
MIRAGE_SECRET_KEY=$MIRAGE_SECRET_KEY
MIRAGE_CIPHER_IV=$MIRAGE_CIPHER_IV

# MySQL, docker-compose-mysql-rabbitmq.yml only. Both values must stay equal
# while MYSQL_USER is root: the engine, the healthcheck and Grafana all
# authenticate as root with MYSQL_PASSWORD.
MYSQL_PASSWORD=$MYSQL_PASSWORD
MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

# RabbitMQ, docker-compose-mysql-rabbitmq.yml only. The username is rabbitmq.
RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD

# Grafana admin password, for the bundled grafana service.
GRAFANA_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
ENVFILE

if [ "$DEMO" -eq 1 ]; then
	DEMO_USERS_PASSWORD="$(random_alnum 24)"
	cat >>"$ENV_FILE" <<ENVFILE

# Shared password for the demo accounts a demo-seeding script may create.
DEMO_USERS_PASSWORD=$DEMO_USERS_PASSWORD
ENVFILE
fi

chmod 600 "$ENV_FILE"

printf '\n'
printf 'Wrote %s/.env (mode 600) with freshly generated credentials.\n' "$(pwd)"
printf '\n'
printf 'Grafana admin login -- this is the only time the password is shown:\n'
printf '\n'
printf '    user:     %s\n' "$GRAFANA_USER"
printf '    password: %s\n' "$GRAFANA_ADMIN_PASSWORD"
printf '\n'
printf 'It is stored in .env as GRAFANA_ADMIN_PASSWORD. To rotate it, re-run\n'
printf 'this script with --force and restart the stack.\n'
if [ "$DEMO" -eq 1 ]; then
	printf '\n'
	printf 'Demo mode: DEMO_USERS_PASSWORD was generated into .env (not shown here).\n'
fi
printf '\n'
printf 'Next: docker compose up -d\n'
